steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/repo-sub/auth', '.' ]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-east1-docker.pkg.dev/$PROJECT_ID/repo-sub/auth']

options:
  logging: CLOUD_LOGGING_ONLY